-- ============================================================================
-- RLS : écriture sur stock_medicaments réservée au pharmacien en chef
-- ============================================================================
--
-- STATUT : déjà en place et vérifié le 2026-07-16. Aucune action nécessaire.
--
-- La base contient déjà exactement les politiques requises :
--   - stock_insertion_chef  (INSERT) → with_check : is_chief_pharmacien(site_id)
--   - stock_maj_chef        (UPDATE) → using/with_check : is_chief_pharmacien(site_id)
--   - stock_suppression_chef(DELETE) → using : is_chief_pharmacien(site_id)
--   - stock_lecture         (SELECT) → admin OU même site (lecture seule pour
--                                       les pharmaciens non-chefs, comme voulu)
--
-- Et la fonction sous-jacente fait bien la bonne vérification :
--
--   CREATE OR REPLACE FUNCTION public.is_chief_pharmacien(p_site_id uuid)
--    RETURNS boolean
--    LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public'
--   AS $function$
--     select exists(select 1 from public.sites where id = p_site_id and pharmacien_chef_id = auth.uid());
--   $function$
--
-- Combiné à la restriction côté interface (commit 418d6e2 : bouton "Modifier"
-- masqué pour les non-chefs), la protection est donc effective aux deux niveaux
-- - même un contournement de l'UI (ex. console navigateur) serait bloqué par
-- ces politiques.
--
-- Requêtes utilisées pour vérifier ci-dessus, à réutiliser si le schéma change :
--
--   select policyname, cmd, roles, qual, with_check
--   from pg_policies
--   where schemaname = 'public' and tablename = 'stock_medicaments';
--
--   select prosrc from pg_proc where proname = 'is_chief_pharmacien';
-- ============================================================================
